# exampleNet_params.py
# Automatically generated by Netflux2 on 2025-03-15
import numpy as np

def loadParams():
    # species parameters
    speciesIDs = ['A', 'B', 'C', 'D', 'E']
    y0 = np.array([0, 0, 0, 0, 0])
    ymax = np.array([1, 1, 1, 1, 1])
    tau = np.array([1, 1, 1, 1, 1])

    # reaction parameters
    w = np.array([0, 0, 1, 1, 1, 1])
    n = np.array([1.4, 1.4, 1.4, 1.4, 1.4, 1.4])
    EC50 = np.array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

    return speciesIDs, y0, ymax, tau, w, n, EC50