# exampleNet_run.py
# Automatically generated by Netflux2 on 2025-03-15
import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
import exampleNet
import exampleNet_params

speciesNames, y0, ymax, tau, w, n, EC50 = exampleNet_params.loadParams()

# Run single simulation
tspan = [0, 10]
solution = solve_ivp(exampleNet.ODEfunc, tspan, y0, args=(ymax, tau, w, n, EC50))

fig, ax = plt.subplots()
ax.plot(solution.t,solution.y.T)
ax.set(xlabel='Time',ylabel='Normalized activity')
ax.legend(speciesNames)